alias dir="ls -Alh"
alias venv="virtualenv --no-site-packages venv"
alias activate=". venv/bin/activate"
alias venv3="virtualenv --python=python3 --no-site-packages venv3"
alias activate3=". venv3/bin/activate"
alias download="wget -c -t0"
alias sss="ssh -p2222"
alias untar="tar xvf"
