alias dir="ls -Alh --time-style=long-iso"
alias venv="virtualenv --no-site-packages venv"
alias activate=". venv/bin/activate"
alias download="wget -c -t0"
alias sss="ssh -p2222"
alias untar="tar xvf"
